### ISSUE TITLE
Preview mode for layout preview in IDE

### ISSUE THREAD

**Issue by challme28** [AlmogBaku/IntlPhoneInput#4]
I just created a new project compileSdkVersion 23 and minSdkVersion 15. Added the dependency at gradle and Added the XML to the activity_main default layout and the following error appears:

java.lang.ClassNotFoundException: android.telephony.PhoneNumberFormattingTextWatcher...

Is it just me?

EDIT: It does compile and works fine, but is there a way i can preview it?

**Comment by AlmogBaku** [comment]
Currently there is no way to "preview" this..
It's a little bit complicated to achieve this function, would love to get a PR on this issue
